spring:
  application:
    name: dev-interview-simulator

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev_interview_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/migration/V2__add_code_review_support.sql
        - classpath:data.sql
        - classpath:db/seed/V2_1__code_review_seeds.sql

server:
  port: 8080